[package]
name = "voicefile_name_changer"
version = "0.4.3"
edition = "2021"

[dependencies]
get_input = { git = "https://github.com/Uliboooo/get_input" }
clap = { version = "4.5.*", features = ["derive"] }
# colored = "1.*"
# tempfile = "3.14.*"
