[package]
name = "voicefile_name_changer"
version = "0.3.0"
edition = "2021"

[dependencies]
get_input = { git = "https://github.com/ulibo-yuki/get_input"}
clap = { version = "4.5.*", features = ["derive"] }
# colored = "1.*"
